"""Add is_seen_by_landlord to Application model

Revision ID: 1762551d3da4
Revises: bc25760349d6
Create Date: 2025-07-27 21:56:59.071796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1762551d3da4'
down_revision = 'bc25760349d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seen_by_landlord', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('is_seen_by_landlord')

    # ### end Alembic commands ###
