"""Add credit_check_path to applications table

Revision ID: 39d3b2ba6a72
Revises: a2c2c2b1e4c7
Create Date: 2025-07-30 11:07:50.044292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d3b2ba6a72'
down_revision = 'a2c2c2b1e4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_check_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('credit_check_path')

    # ### end Alembic commands ###
