"""Add last_message_body to Conversation

Revision ID: 4fddf5292181
Revises: 1762551d3da4
Create Date: 2025-07-28 00:45:14.469752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fddf5292181'
down_revision = '1762551d3da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_body', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('last_message_body')

    # ### end Alembic commands ###
