"""Add seen flag to bookings

Revision ID: 699dd691bb7c
Revises: eb0f7cf365e1
Create Date: 2025-07-09 20:16:21.426799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699dd691bb7c'
down_revision = 'eb0f7cf365e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seen_by_landlord', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('is_seen_by_landlord')

    # ### end Alembic commands ###
