"""Add Application model

Revision ID: 771ff9a95ab7
Revises: 4fddf5292181
Create Date: 2025-07-27 20:50:32.699618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771ff9a95ab7'
down_revision = '4fddf5292181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seen_by_landlord', sa.Boolean(), nullable=False))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_body', sa.String(length=255), nullable=True))

    with op.batch_alter_table('viewing_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landlord_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['landlord_id'], ['id'])
        batch_op.drop_column('property_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewing_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])
        batch_op.drop_column('landlord_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('last_message_body')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('is_seen_by_landlord')

    # ### end Alembic commands ###
