"""Link Booking and ViewingSlot models

Revision ID: d105b25e94b5
Revises: 6a98ad2ef7a3
Create Date: 2025-07-22 22:45:10.495244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd105b25e94b5'
down_revision = '6a98ad2ef7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewing_slot_id', sa.Integer(), nullable=True))
        # Naming the constraints to fix the error
        batch_op.create_unique_constraint('uq_bookings_viewing_slot_id', ['viewing_slot_id'])
        batch_op.create_foreign_key('fk_bookings_viewing_slot_id_viewing_slots', 'viewing_slots', ['viewing_slot_id'], ['id'])

    # The rest of the original upgrade function can be removed as it's not needed for this change.
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        # Using the same names to drop the constraints
        batch_op.drop_constraint('fk_bookings_viewing_slot_id_viewing_slots', type_='foreignkey')
        batch_op.drop_constraint('uq_bookings_viewing_slot_id', type_='unique')
        batch_op.drop_column('viewing_slot_id')

    # The rest of the original downgrade function can be removed.
    # ### end Alembic commands ###
